apiVersion: v1
kind: Service
metadata:
  name: order-ingestion
  namespace: crypto-oms
  labels:
    app: order-ingestion
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: order-ingestion
  sessionAffinity: None
