apiVersion: v1
kind: Service
metadata:
  name: risk-engine
  namespace: crypto-oms
  labels:
    app: risk-engine
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: risk-engine
  sessionAffinity: None
